services:
  - type: web
    name: django-todo-app
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"